sudo: required
dist: trusty
language: php

cache:
  bundler: true
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"
php:
  - 5.6
env:
  matrix:
    - VERSION=HEAD
  global:
    - SAUCE_USERNAME=pipelines
    - SAUCE_ACCESS_KEY=70c642c9-b9f4-4439-8816-9372dab0d6d0

addons:
  sauce_connect: true


before_script:
  # Start Sauce Connect - a magical rainbow tunnel.
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash

script:
  - behat --strict

matrix:
  fast_finish: true
