sudo: required
dist: trusty
language: php

cache:
  bundler: true
  apt: true
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.npm"
php:
  - 5.6
env:
  matrix:
    - VERSION=HEAD
    - VERSION=2.0.3
    - VERSION=2.0.2
    - VERSION=2.0.1
    - VERSION=2.0.0
  global:
    - SAUCE_USERNAME=pipelines
    - SAUCE_ACCESS_KEY=70c642c9-b9f4-4439-8816-9372dab0d6d0

addons:
  sauce_connect: true

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$HOME/.composer/vendor/bin:$TRAVIS_BUILD_DIR/bin:$PATH"

  # composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  # Create the MySQL database and add a user for testing.
  - mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'lightning'@'localhost' IDENTIFIED BY 'lightning'; GRANT ALL ON drupal.* TO 'lightning'@'localhost';"

  # Install the PECL YAML extension for strict parsing. yes is used to
  # acknowledge all prompts.
  - yes '' | pecl install yaml
  # Tweak PHP configuration.
  - echo 'max_execution_time = 120' >> drupal.php.ini;
  - echo 'sendmail_path = /bin/true' >> drupal.php.ini;
  - phpenv config-add drupal.php.ini
  - phpenv rehash

  # We need Phing to execute our build steps.
  - composer global require phing/phing
  # Build the Lightning code base.
  - composer install
  # Install Lightning cleanly so that settings.php will be created properly.
  - phing install -Ddb.database=drupal -Ddb.user=lightning -Ddb.password=lightning -Ddb.host=127.0.0.1
  # Import the fixture, if it exists.
  - phing remember -Dversion=$VERSION -Ddb.database=drupal -Ddb.user=lightning -Ddb.password=lightning -Ddb.host=127.0.0.1
  - cd docroot
  # Execute database updates, if there are any.
  - drush updatedb --yes

before_script:
  - drush runserver --default-server=builtin 8080 &>/dev/null &
  # Start Sauce Connect - a magical rainbow tunnel.
  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
  - sleep 5
  - cd ./profiles/lightning

script:
  - composer validate --no-check-all --ansi
  - behat --tags=~saucelabs

matrix:
  fast_finish: true
